DROP DATABASE IF EXISTS Library;

CREATE DATABASE Library;
USE Library;
-- your code here to build the library
CREATE TABLE Customer (
	ID 	NUMERIC(9) NOT NULL,
	CHECK_OUT 			VARCHAR(40),
	CHECK_IN			VARCHAR(40),
  PUT_HOLD      VARCHAR(40),
  CANCEL_HOLD   VARCHAR(40),
  NAME          VARCHAR(40),
	PRIMARY KEY (ID)
);

CREATE TABLE StaffMember (
	ID 	NUMERIC(9) NOT NULL,
  REMOVE_BOOK			VARCHAR(40),
  MOVE_BOOK       VARCHAR(40),
  FIND_CUSTOMER   VARCHAR(40),
  CREATE_MEMBER   VARCHAR(40),
  SALARY          NUMERIC(9),
  WORKTIME        VARCHAR(40),
  DUTIES          VARCHAR(40),
	PRIMARY KEY (ID)
);

CREATE TABLE Administrator (
	ID 	NUMERIC(9) NOT NULL,
	SEARCHSTAFF 	VARCHAR(40),
	LISTSTAFF			VARCHAR(40),
  SALARYSTAFF   VARCHAR(40),
  REVOKEMEMBERSHIP  VARCHAR(40),
  HIRESTAFF     VARCHAR(40),
  FIRESTAFF     VARCHAR(40),
	PRIMARY KEY (ID)
);

CREATE TABLE Books (
  BOOKID           NUMERIC(9) NOT NULL,
  TITLE        VARCHAR(40),
  AUTHOR       VARCHAR(40),
  NUMBEROFCOPIES    NUMERIC(5),
  GENRE        VARCHAR(40),
  PRIMARY KEY (BOOKID)
);

CREATE TABLE BookDetails (
  BOOKID      VARCHAR(40) NOT NULL,
  TITLE       VARCHAR(40),
  AUTHOR      VARCHAR(40),
  LOCATION     VARCHAR(40),
  AVAILABLE    VARCHAR(40),
  ISDAMAGED    VARCHAR(40),
  BOOKBARCODE  NUMERIC(9),
  ONHOLD       VARCHAR(40),
  CUSTOMERID   NUMERIC(9),
  PRIMARY KEY(BOOKID)
);

CREATE TABLE WorkShifts(
  StaffID   NUMERIC(9) NOT NULL,
  WORKEDON  VARCHAR(40),
  WillWork  VARCHAR(40),
  PRIMARY KEY(StaffID)
);

CREATE TABLE CheckOutandIn(
  CustomerID  NUMERIC(9) NOT NULL,
  WhenCheckedOut  VARCHAR(40),
  WhenCheckedIn   VARCHAR(40),
  PopularGenre    VARCHAR(40),
  BooksID     NUMERIC(9),
  PRIMARY KEY(CustomerID)
);

CREATE TABLE BooksByMonth(
  Month   VARCHAR(40) NOT NULL,
  HowManyOut NUMERIC(40),
  HowManyIn  NUMERIC(40),
  WhichYear  NUMERIC(40),
  PRIMARY KEY(Month)
);

-- end code block